import { Message } from "./interfaces";

const peer1 = new Uint8Array([101, 102, 103]);
const peer2 = new Uint8Array([201, 202, 203]);
const peer3 = new Uint8Array([301, 302, 304]);

export const fakeMessageData1: Message[] = [
    //       NOTE: if the first one is removed (for testing), the order is shifted around
    //       which is ok because it just needs to go from lowest round to highest round
    
    // PEER 1 
{
    id: new Uint8Array([1, 2, 3]),
    peer: peer1,
    parent: null,
    height: 1,
    acks: [],
    type: "message",
    round: 1,
    channel: "channel",
    data: "white",
    status: "confirmed",
},
{
    id: new Uint8Array([4, 5, 6]),
    peer: peer1,
    parent: new Uint8Array([1, 2, 3]),
    height: 1,
    acks: [new Uint8Array([10, 11, 12]),new Uint8Array([19, 20, 21]),],
    type: "message",
    round: 2,
    channel: "channel",
    data: "white",
    status: "confirmed",
},
{
    id: new Uint8Array([7, 8, 9]),
    peer: peer1,
    parent: new Uint8Array([4, 5, 6]),
    height: 1,
    acks: [new Uint8Array([13, 14, 15]),new Uint8Array([22, 23, 24]),],
    type: "message",
    round: 3,
    channel: "channel",
    data: "white",
    status: "confirmed",
},
{
    id: new Uint8Array([28, 29, 30]),
    peer: peer1,
    parent: new Uint8Array([7, 8, 9]),
    height: 1,
    acks: [new Uint8Array([16, 17, 18]),new Uint8Array([25, 26, 27]),],
    type: "message",
    round: 4,
    channel: "channel",
    data: "white",
    status: "confirmed",
},

    // PEER 2
{
    id: new Uint8Array([10, 11, 12]),
    peer: peer2,
    parent: null,
    height: 1,
    acks: [],
    type: "message",
    round: 1,
    channel: "channel",
    data: "white",
    status: "confirmed",
},
{
    id: new Uint8Array([13, 14, 15]),
    peer: peer2,
    parent: new Uint8Array([10, 11, 12]),
    height: 1,
    acks: [new Uint8Array([1, 2, 3]),new Uint8Array([19, 20, 21]),],
    type: "message",
    round: 2,
    channel: "channel",
    data: "white",
    status: "confirmed",
},
{
    id: new Uint8Array([16, 17, 18]),
    peer: peer2,
    parent: new Uint8Array([13, 14, 15]),
    height: 1,
    acks: [new Uint8Array([4, 5, 6]),new Uint8Array([22, 23, 24]),],
    type: "message",
    round: 3,
    channel: "channel",
    data: "white",
    status: "confirmed",
},

    // PEER 3
{
    id: new Uint8Array([19, 20, 21]),
    peer: peer3,
    parent: null,
    height: 1,
    acks: [],
    type: "message",
    round: 1,
    channel: "channel",
    data: "white",
    status: "confirmed",
},
{
    id: new Uint8Array([22, 23, 24]),
    peer: peer3,
    parent: new Uint8Array([19, 20, 21]),
    height: 1,
    acks: [new Uint8Array([1, 2, 3]),new Uint8Array([10, 11, 12]),],
    type: "message",
    round: 2,
    channel: "channel",
    data: "white",
    status: "confirmed",
},
{
    id: new Uint8Array([25, 26, 27]),
    peer: peer3,
    parent: new Uint8Array([22, 23, 24]),
    height: 1,
    acks: [new Uint8Array([4, 5, 6]),new Uint8Array([13, 14, 15]),],
    type: "message",
    round: 3,
    channel: "channel",
    data: "white",
    status: "confirmed",
},
];



export const fakeMessageData2: Message[] = [
    // PEER 1
    {
        id: new Uint8Array([1, 2, 3]),
        peer: peer1,
        parent: null,
        height: 1,
        acks: [],
        type: "message",
        round: 1,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([4, 5, 6]),
        peer: peer1,
        parent: new Uint8Array([1, 2, 3]),
        height: 2,
        acks: [new Uint8Array([10, 11, 12]), new Uint8Array([19, 20, 21])],
        type: "message",
        round: 2,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([7, 8, 9]),
        peer: peer1,
        parent: new Uint8Array([4, 5, 6]),
        height: 3,
        acks: [new Uint8Array([13, 14, 15]), new Uint8Array([22, 23, 24])],
        type: "message",
        round: 3,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([28, 29, 30]),
        peer: peer1,
        parent: new Uint8Array([7, 8, 9]),
        height: 4,
        acks: [new Uint8Array([16, 17, 18]), new Uint8Array([25, 26, 27])],
        type: "message",
        round: 4,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([31, 32, 33]),
        peer: peer1,
        parent: new Uint8Array([28, 29, 30]),
        height: 5,
        acks: [new Uint8Array([37, 38, 39]), new Uint8Array([46, 47, 48])],
        type: "message",
        round: 5,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([34, 35, 36]),
        peer: peer1,
        parent: new Uint8Array([31, 32, 33]),
        height: 6,
        acks: [new Uint8Array([40, 41, 42]), new Uint8Array([49, 50, 51])],
        type: "message",
        round: 6,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },

    // PEER 2
    {
        id: new Uint8Array([10, 11, 12]),
        peer: peer2,
        parent: null,
        height: 1,
        acks: [],
        type: "message",
        round: 1,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([13, 14, 15]),
        peer: peer2,
        parent: new Uint8Array([10, 11, 12]),
        height: 2,
        acks: [new Uint8Array([1, 2, 3]), new Uint8Array([19, 20, 21])],
        type: "message",
        round: 2,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([16, 17, 18]),
        peer: peer2,
        parent: new Uint8Array([13, 14, 15]),
        height: 3,
        acks: [new Uint8Array([4, 5, 6]), new Uint8Array([22, 23, 24])],
        type: "message",
        round: 3,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([37, 38, 39]),
        peer: peer2,
        parent: new Uint8Array([16, 17, 18]),
        height: 4,
        acks: [new Uint8Array([7, 8, 9]), new Uint8Array([25, 26, 27])],
        type: "message",
        round: 4,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([40, 41, 42]),
        peer: peer2,
        parent: new Uint8Array([37, 38, 39]),
        height: 5,
        acks: [new Uint8Array([28, 29, 30]), new Uint8Array([46, 47, 48])],
        type: "message",
        round: 5,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([43, 44, 45]),
        peer: peer2,
        parent: new Uint8Array([40, 41, 42]),
        height: 6,
        acks: [new Uint8Array([31, 32, 33]), new Uint8Array([49, 50, 51])],
        type: "message",
        round: 6,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },

    // PEER 3
    {
        id: new Uint8Array([19, 20, 21]),
        peer: peer3,
        parent: null,
        height: 1,
        acks: [],
        type: "message",
        round: 1,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([22, 23, 24]),
        peer: peer3,
        parent: new Uint8Array([19, 20, 21]),
        height: 2,
        acks: [new Uint8Array([1, 2, 3]), new Uint8Array([10, 11, 12])],
        type: "message",
        round: 2,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([25, 26, 27]),
        peer: peer3,
        parent: new Uint8Array([22, 23, 24]),
        height: 3,
        acks: [new Uint8Array([4, 5, 6]), new Uint8Array([13, 14, 15])],
        type: "message",
        round: 3,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([46, 47, 48]),
        peer: peer3,
        parent: new Uint8Array([25, 26, 27]),
        height: 4,
        acks: [new Uint8Array([7, 8, 9]), new Uint8Array([16, 17, 18])],
        type: "message",
        round: 4,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([49, 50, 51]),
        peer: peer3,
        parent: new Uint8Array([46, 47, 48]),
        height: 5,
        acks: [new Uint8Array([28, 29, 30]), new Uint8Array([37, 38, 39])],
        type: "message",
        round: 5,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([55, 56, 57]),
        peer: peer3,
        //parent: new Uint8Array([46, 47, 48]),
        parent: null,
        height: 5,
        //acks: [new Uint8Array([28, 29, 30]), new Uint8Array([37, 38, 39])],
        acks: [],
        type: "message",
        round: 5,
        channel: "channel",
        data: "red",
        status: "confirmed",
    },
    {
        id: new Uint8Array([52, 53, 54]),
        peer: peer3,
        parent: new Uint8Array([49, 50, 51]),
        height: 6,
        acks: [new Uint8Array([31, 32, 33]), new Uint8Array([40, 41, 42])],
        type: "message",
        round: 6,
        channel: "channel",
        data: "white",
        status: "confirmed",
    },
    {
        id: new Uint8Array([58, 59, 60]),
        peer: peer3,
        parent: new Uint8Array([55, 56, 57]),
        //parent: null,
        height: 6,
        //acks: [new Uint8Array([28, 29, 30]), new Uint8Array([37, 38, 39])],
        acks: [],
        type: "message",
        round: 6,
        channel: "channel",
        data: "red",
        status: "confirmed",
    },
];